FROM php:__PHP_VERSION__

# Use (almost) the default production configuration
RUN sed -re 's/^(expose_php)(.+)/\1=Off/' "$PHP_INI_DIR"/php.ini-production \
    > "$PHP_INI_DIR/php.ini"

COPY opcache.ini $PHP_INI_DIR/conf.d/
